enum StorageResponseStatus {
  dBCreated,
  failedDBCreated,
  errorReading,
  alreadyRegistered,
  limitReached,
  itemCreated,
  errorWriting,
  itemUpdated,
  errorUpdating,
  itemDeleted,
  errorDeleting,
  notFound,
  emptyList,
  errorReadingAll,
}
